#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NativePortable.Droid.Resource", IsApplication=true)]

namespace NativePortable.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int activity_main = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int adapter_item_tvAge = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int adapter_item_tvId = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int adapter_item_tvLastName = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int adapter_item_tvMail = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int adapter_item_tvName = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int adapter_item_tvPhone = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int dao_view_bBack = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int dao_view_lvPersons = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int main_activity_bCreate = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int main_activity_bDelete = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int main_activity_bRead = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int main_activity_bReadAll = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int main_activity_bUpdate = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int main_activity_etAge = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int main_activity_etId = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int main_activity_etLastName = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int main_activity_etMail = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int main_activity_etName = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int main_activity_etPhone = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int main_activity_frame = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int main_activity_spinnerDB = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int adapter_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_dao_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_test = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int button_exit = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int ma_age = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int ma_bCreate = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int ma_bDelete = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int ma_bRead = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int ma_bReadAll = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int ma_bUpdate = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int ma_id = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ma_lastName = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int ma_mail = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int ma_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int ma_phone = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
