#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XOClientXamarin.Droid.Resource", IsApplication=true)]

namespace XOClientXamarin.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int dialog_changePass_etNewPassword = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int dialog_changePass_etPassword = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int dialog_changePass_etUsername = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int fragment_game = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int fragment_game_b1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int fragment_game_b2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int fragment_game_b3 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int fragment_game_b4 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int fragment_game_b5 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int fragment_game_b6 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int fragment_game_b7 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int fragment_game_b8 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int fragment_game_b9 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int fragment_game_bExit = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int fragment_game_tvStatusBar = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int fragment_lobby = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int fragment_lobby_bLogin = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int fragment_lobby_bLogout = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int fragment_lobby_lvFreePlayersList = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int fragment_lobby_tvStatusBar = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int fragment_lobby_tvStatusBar_name = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int fragment_ra = 2131034112;
			
			// aapt resource value: 0x7f050018
			public const int fragment_ra_bAuth = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int fragment_ra_bChangePass = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int fragment_ra_bForgotPass = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int fragment_ra_bReg = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int fragment_ra_etPassword = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int fragment_ra_etUsername = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int lobby_list_item = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int lobby_list_item_tvName = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int main_activity_fragment_placeholder = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_change_password = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_lobby = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_ra = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int lobby_list_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int button_auth = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int button_changePass = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int button_empty = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int button_exit = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int button_forgotPass = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int button_login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int button_logout = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int button_reg = 2130968581;
			
			// aapt resource value: 0x7f04001a
			public const int changepass_dialog_header = 2130968602;
			
			// aapt resource value: 0x7f040014
			public const int dialog_cancel_button = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int dialog_confirm_button = 2130968597;
			
			// aapt resource value: 0x7f04000c
			public const int edittext_newPassword = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int edittext_password = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int edittext_username = 2130968579;
			
			// aapt resource value: 0x7f040010
			public const int facebook_app_id = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int lobby_list_item_name = 2130968591;
			
			// aapt resource value: 0x7f040021
			public const int messagebox_auth_header = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int messagebox_auth_message = 2130968610;
			
			// aapt resource value: 0x7f040029
			public const int messagebox_changepass_dialog_error_message = 2130968617;
			
			// aapt resource value: 0x7f040028
			public const int messagebox_changepass_dialog_success_message = 2130968616;
			
			// aapt resource value: 0x7f04001f
			public const int messagebox_forgotpass_header = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int messagebox_forgotpass_message = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int messagebox_game_over_header = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int messagebox_game_over_message = 2130968601;
			
			// aapt resource value: 0x7f040025
			public const int messagebox_invitation_box_header = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int messagebox_invitation_box_message_l = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int messagebox_invitation_box_message_r = 2130968615;
			
			// aapt resource value: 0x7f04002a
			public const int messagebox_invitation_feedback_header = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int messagebox_invitation_feedback_message = 2130968619;
			
			// aapt resource value: 0x7f040016
			public const int messagebox_invitation_header = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int messagebox_invitation_message = 2130968599;
			
			// aapt resource value: 0x7f04001b
			public const int messagebox_passretrieval_dialog_header = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int messagebox_passretrieval_dialog_message = 2130968604;
			
			// aapt resource value: 0x7f040023
			public const int messagebox_reg_header = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int messagebox_reg_message = 2130968612;
			
			// aapt resource value: 0x7f04001d
			public const int passretrieval_dialog_header = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int passretrieval_dialog_message = 2130968606;
			
			// aapt resource value: 0x7f040012
			public const int status_connected_to_server = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int status_player_name = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int status_waiting_for_connection = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int textview_lobby_statusbar = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int textview_lobby_statusbar_name = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int textview_statusbar = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
