#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("myNewCalc.Droid.Resource", IsApplication=true)]

namespace myNewCalc.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int RoundedView = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int add_balls_btn = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int add_btn = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int buttonsFrameLayout = 2131165187;
			
			// aapt resource value: 0x7f070017
			public const int calcLayout = 2131165207;
			
			// aapt resource value: 0x7f070013
			public const int clear_btn = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int div_btn = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int equals_btn = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int flBalls = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int frameLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int imgView = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int mul_btn = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int num0_btn = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int num1_btn = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int num2_btn = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int num3_btn = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int num4_btn = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int num5_btn = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int num6_btn = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int num7_btn = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int num8_btn = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int num9_btn = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int sub_btn = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070015
			public const int timer_btn = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Balls = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Calc = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int style_btn = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
